### ISSUE TITLE
Ideas...

### ISSUE THREAD

**Issue by vanja-san** [stefan3372/The-WItcher-3-Mod-manager#3]
- Add function of _hiding columns_ in main window.
- Add column **_Version_** .
- Add button to hide right window and console.
- Do something like **_Themes_** so for change icons.
- In the **_About_** window, add a link to _GitHub_ and there move _link to home page_.
- **_Run Script Merger_** and **_Run the Game_** move to top, at bottom it does not need anything.
- Add text under icons, for complete clarity.

**_Example using with Photoshop!_**
![2018-02-19-00-33-59](https://user-images.githubusercontent.com/7201687/36355123-0980b286-1511-11e8-8524-ac161efd5d08.png)
- Submenu (But it is not exactly...)
![-1](https://user-images.githubusercontent.com/7201687/36355124-0d3b679a-1511-11e8-94b8-b55d2d6c022e.png)

**Comment by stefan3372** [comment]
Thanks for the feedback, will consider all suggested options

**Comment by vanja-san** [comment]
And add **Portable version**!
