### ISSUE TITLE
Dont visible mod...

### ISSUE THREAD

**Issue by vanja-san** [stefan3372/The-WItcher-3-Mod-manager#4]
When installing the mod, it did not appear in the _MM_, but it was installed in _mods_ folder!

> In console this text:
> `"ascii" codec can't encode characters in position 0-2: original not in range(128)`

**Mod:** AMM - The Appearances Menu Mod
**Version MM:** 0.5
**System:** Windows 10 x64

Another folder **Witcher 3 Mod Manager** is created in **Documents**. You should do so that folder is saved next to _TheWitcher3ModManager.exe_.

**Comment by stefan3372** [comment]
Please try with the new 0.5.1 version, i have tested AMM on it, and it worked.

Folder in documents is probably going to be changed in the future

**Comment by vanja-san** [comment]
Anyway also.
![2018-05-09-01-50-42](https://user-images.githubusercontent.com/7201687/39776593-7eaf0b9a-532b-11e8-9e44-7c31bfba4444.png)

**Comment by vanja-san** [comment]
I found problem!
Whole problem is that mods are not displayed in Russian version, but in English are displayed.
Maybe it's worth re-translating into Russian?
Tell me what file to take as a basis and translate it into Russian.

How in Russian version:

----------
![2018-05-09-01-56-44](https://user-images.githubusercontent.com/7201687/39776904-55243902-532c-11e8-9245-b35ea45aaf04.png)

How in English version:

---------
![2018-05-09-01-56-13](https://user-images.githubusercontent.com/7201687/39776925-62331b72-532c-11e8-8777-4e9124793077.png)

**Comment by stefan3372** [comment]
Thank you for pinpointing the problem, it is fixed now in 0.5.2
